KafkaServer {
  com.sun.security.auth.module.Krb5LoginModule required
  serviceName="kafka"
  useKeyTab=true
  storeKey=true
  keyTab="/share/keytabs/kafka/kafka.service.keytab"
  principal="kafka/kafka.orb.local@TEST.ORG";
};
