---
- name: compile template files

  hosts: local
  gather_facts: no

  tasks:
    - name: orchestrate basic files
      ansible.builtin.template:
        src: templates/{{ item.file }}.j2
        dest: "{{ playbook_dir }}/{{ item.file }}"
        mode: "{{ item.mode }}"
      with_items:
        - { file: ".env", mode: "a+x" }
        - { file: "build-image.sh", mode: "a+x" }
        - { file: "download.sh", mode: "a+x" }
        - { file: "base-ubuntu-2004/Dockerfile", mode: ~ }

    - include_tasks: node-template.yaml
      loop:
        - name: "hadoop-master1"
          group: "hadoop-master"
        - name: "hadoop-worker1"
          group: "hadoop-worker"
        - name: "hadoop-worker2"
          group: "hadoop-worker"
        - name: "hadoop-worker3"
          group: "hadoop-worker"
      loop_control:
        loop_var: node

    - name: orchestrate compose file
      ansible.builtin.template:
        src: templates/compose.yaml.j2
        dest: "{{ playbook_dir }}/compose.yaml"
