#jinja2: trim_blocks: True, lstrip_blocks: True
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG PROJECT_VERSION
FROM hadoop-testing/base-ubuntu-2004:$PROJECT_VERSION

ARG HADOOP_VERSION
ARG HBASE_VERSION
ARG SPARK_VERSION
ARG TRINO_VERSION

ENV HADOOP_HOME=/opt/hadoop
ENV HADOOP_CONF_DIR=/etc/hadoop/conf
ENV LD_LIBRARY_PATH=${HADOOP_HOME}/lib/native
{% if hbase_enabled %}
ENV HBASE_HOME=/opt/hbase
ENV HBASE_CONF_DIR=/etc/hbase/conf
{% endif %}
{% if trino_enabled %}
ENV TRINO_HOME=/opt/trino
{% endif %}
ENV PATH=${HADOOP_HOME}/bin:${PATH}
{% if hbase_enabled %}
ENV PATH=${HBASE_HOME}/bin:${PATH}
{% endif %}

ADD download/hadoop-${HADOOP_VERSION}.tar.gz /opt
{% if hbase_enabled %}
ADD download/hbase-${HBASE_VERSION}-hadoop3-bin.tar.gz /opt
{% endif %}
ADD download/spark-${SPARK_VERSION}-bin-{{ spark_custom_name }}/yarn /opt/spark-${SPARK_VERSION}-bin-{{ spark_custom_name }}/yarn
{% if trino_enabled %}
ADD download/trino-server-${TRINO_VERSION}.tar.gz /opt
{% endif %}

# Copy configuration files
COPY ./files /

RUN ln -snf /opt/hadoop-${HADOOP_VERSION} ${HADOOP_HOME} && \
    ln -snf spark-${SPARK_VERSION}-bin-{{ spark_custom_name }} /opt/spark
{% if trino_enabled %}
RUN ln -snf /opt/trino-server-${TRINO_VERSION} ${TRINO_HOME}
{% endif %}

{% if hbase_enabled %}
RUN rm -rf /opt/hbase-${HBASE_VERSION}-hadoop3/docs && \
    ln -snf /opt/hbase-${HBASE_VERSION}-hadoop3 ${HBASE_HOME} && \
    cp -n ${HBASE_HOME}/conf/* ${HBASE_CONF_DIR}/ && \
    ln -snf ${HADOOP_CONF_DIR}/core-site.xml ${HBASE_CONF_DIR}/core-site.xml && \
    ln -snf ${HADOOP_CONF_DIR}/hdfs-site.xml ${HBASE_CONF_DIR}/hdfs-site.xml && \
    mkdir -p /var/log/hbase /var/run/hbase /var/lib/hbase && \
    chown -R hbase:hbase /var/log/hbase /var/run/hbase /var/lib/hbase
{% endif %}

RUN chown -R root:hadoop /opt/hadoop-${HADOOP_VERSION} && \
    chmod 6050 /opt/hadoop-${HADOOP_VERSION}/bin/container-executor && \
    chown root:hadoop /etc/hadoop/conf/container-executor.cfg && \
    chmod 0400 /etc/hadoop/conf/container-executor.cfg && \
    mv -f /etc/hadoop/conf/container-executor.cfg /opt/hadoop-${HADOOP_VERSION}/etc/hadoop

RUN /opt/hadoop-init.d/init-hdfs.sh
{% if trino_enabled %}
RUN mkdir /var/trino && chown -R trino:trino /var/trino
{% endif %}

# HDFS ports
EXPOSE 1004 1006 8020 9866 9867 9870 9864 50470

# YARN ports
EXPOSE 8030 8031 8032 8033 8040 8041 8042 8088 10020 19888

{% if hbase_enabled %}
# HBase ports
EXPOSE 16020 16030
{% endif %}

CMD supervisord -c /etc/supervisord.conf
