#jinja2: trim_blocks: True, lstrip_blocks: True
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG PROJECT_VERSION
FROM hadoop-testing/base-ubuntu-2004:$PROJECT_VERSION

ARG HADOOP_VERSION
ARG SPARK_VERSION
ARG TRINO_VERSION

ENV HADOOP_HOME=/opt/hadoop
ENV HADOOP_CONF_DIR=/etc/hadoop/conf
ENV LD_LIBRARY_PATH=${HADOOP_HOME}/lib/native
{% if trino_enabled %}
ENV TRINO_HOME=/opt/trino
{% endif %}
ENV PATH=${HADOOP_HOME}/bin:${PATH}

ADD download/hadoop-${HADOOP_VERSION}.tar.gz /opt
ADD download/spark-${SPARK_VERSION}-bin-hadoop3/yarn /opt/spark-${SPARK_VERSION}-bin-hadoop3/yarn
{% if trino_enabled %}
ADD download/trino-server-${TRINO_VERSION}.tar.gz /opt
{% endif %}

# Copy configuration files
COPY ./files /

RUN ln -snf /opt/hadoop-${HADOOP_VERSION} ${HADOOP_HOME} && \
    ln -snf spark-${SPARK_VERSION}-bin-hadoop3 /opt/spark
{% if trino_enabled %}
RUN ln -snf /opt/trino-server-${TRINO_VERSION} ${TRINO_HOME}
{% endif %}

RUN chown -R root:hadoop /opt/hadoop-${HADOOP_VERSION} && \
    chmod 6050 /opt/hadoop-${HADOOP_VERSION}/bin/container-executor && \
    chown root:hadoop /etc/hadoop/conf/container-executor.cfg && \
    chmod 0400 /etc/hadoop/conf/container-executor.cfg && \
    mv -f /etc/hadoop/conf/container-executor.cfg /opt/hadoop-${HADOOP_VERSION}/etc/hadoop

RUN /opt/hadoop-init.d/init-hdfs.sh
{% if trino_enabled %}
RUN /opt/trino-init.d/init-workdir.sh
{% endif %}

# HDFS ports
EXPOSE 1004 1006 8020 9866 9867 9870 9864 50470

# YARN ports
EXPOSE 8030 8031 8032 8033 8040 8041 8042 8088 10020 19888

CMD supervisord -c /etc/supervisord.conf
