{
 "title": "Kyuubi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "KYUUBI_METRIC_DS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kyuubi_memory_usage_total_init,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Update time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=~\"$instance\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_heap_used{instance=~\"$instance\"}) by (instance) / sum(kyuubi_memory_usage_heap_max{instance=~\"$instance\"}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(sum(kyuubi_memory_usage_non_heap_used{instance=~\"$instance\"}) by (instance) / sum(kyuubi_memory_usage_non_heap_max{instance=~\"$instance\"}) by (instance),0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " kyuubi_memory_usage_total_used",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Eden_Space_used)",
     "legendFormat": "Eden Space Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Eden_Space_committed)",
     "legendFormat": "Eden Space Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Eden_Space_max)",
     "legendFormat": "Eden Space Max"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_pools_CMS_Old_Gen_used)",
     "legendFormat": "Old Gen Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_CMS_Old_Gen_committed)",
     "legendFormat": "Old Gen Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_CMS_Old_Gen_max)",
     "legendFormat": "Old Gen Max"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Survivor_Space_used)",
     "legendFormat": "Survivor Space Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Survivor_Space_committed)",
     "legendFormat": "Survivor Space Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Survivor_Space_max)",
     "legendFormat": "Survivor Space Max"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_pools_Metaspace_used)",
     "legendFormat": "Metaspace Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Metaspace_committed)",
     "legendFormat": "Metaspace Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Metaspace_max)",
     "legendFormat": "Metaspace Max"
    }
   ]
  },
  {
   "title": "Compressed Class",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_pools_Compressed_Class_Space_used)",
     "legendFormat": "Compressed Class Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Compressed_Class_Space_committed)",
     "legendFormat": "Compressed Class Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Compressed_Class_Space_max)",
     "legendFormat": "Compressed Class Max"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kyuubi_memory_usage_pools_Code_Cache_used)",
     "legendFormat": "Code Cache Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Code_Cache_committed)",
     "legendFormat": "Code Cache Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Code_Cache_max)",
     "legendFormat": "Code Cache Max"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Alive Thread",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_exec_pool_threads_alive{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Thread",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_exec_pool_threads_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Engine Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "kyuubi_engine_total\r\n", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Operation Statistics",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyuubi_operation_state_ExecuteStatement_running_total)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kyuubi_operation_state_ExecuteStatement_finished_total)",
     "legendFormat": "Finished"
    },
    {
     "expr": "sum(kyuubi_operation_state_ExecuteStatement_error_total)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(kyuubi_operation_state_ExecuteStatement_pending_total)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Opened",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    { "expr": "kyuubi_connection_opened", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Thrift Binary Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "kyuubi_thrift_binary_connection_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(kyuubi_thread_state_runnable_count)",
     "legendFormat": "Runnable"
    },
    {
     "expr": "sum(kyuubi_thread_state_blocked_count)\r\n",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(kyuubi_thread_state_waiting_count)\r\n",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}