{
 "title": "Kyuubi",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kyuubi_memory_usage_total_init,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_jvm_uptime{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "kyuubi_connection_total_BATCH{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}-batch"
    },
    {
     "expr": "kyuubi_connection_total_INTERACTIVE{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}-interactive"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " kyuubi_memory_usage_total_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_pools_PS_Eden_Space_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Eden Space Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Eden_Space_committed)",
     "legendFormat": "Eden Space Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Eden_Space_max)",
     "legendFormat": "Eden Space Max"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_pools_PS_Old_Gen_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Old Gen Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_CMS_Old_Gen_committed)",
     "legendFormat": "Old Gen Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_CMS_Old_Gen_max)",
     "legendFormat": "Old Gen Max"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_pools_PS_Survivor_Space_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Survivor Space Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Survivor_Space_committed)",
     "legendFormat": "Survivor Space Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Par_Survivor_Space_max)",
     "legendFormat": "Survivor Space Max"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_pools_Metaspace_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Metaspace Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Metaspace_committed)",
     "legendFormat": "Metaspace Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Metaspace_max)",
     "legendFormat": "Metaspace Max"
    }
   ]
  },
  {
   "title": "Compressed Class",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Compressed Class Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Compressed_Class_Space_committed)",
     "legendFormat": "Compressed Class Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Compressed_Class_Space_max)",
     "legendFormat": "Compressed Class Max"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_pools_Code_Cache_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Code Cache Used"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Code_Cache_committed)",
     "legendFormat": "Code Cache Committed"
    },
    {
     "expr": "sum(kyuubi_memory_usage_pools_Code_Cache_max)",
     "legendFormat": "Code Cache Max"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Alive Thread",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_exec_pool_threads_alive{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Thread",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_exec_pool_threads_active{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Engine Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "kyuubi_engine_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Statistics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_running_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_finished_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Finished"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_error_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Error"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_pending_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Opened",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "kyuubi_connection_opened{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thrift Binary Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "kyuubi_thrift_binary_connection_total{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "kyuubi_thread_state_runnable_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "kyuubi_thread_state_blocked_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "kyuubi_thread_state_waiting_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}